name: Sell All Positions

on:
  schedule:
    - cron: '40 19 * * 1-5'  # 5 min before market close in EST (market closes 4PM ET)
  workflow_dispatch:  # allows manual trigger

jobs:
  sell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements_sell.txt

      - name: Run sell_all.py
        env:
          APCA_API_KEY_ID: ${{ secrets.APCA_API_KEY_ID }}
          APCA_API_SECRET_KEY: ${{ secrets.APCA_API_SECRET_KEY }}
        run: python sell_all.py
